#!/bin/bash
# Quick Setup Script for Render.com Deployment
# Run this script to get deployment commands

echo "================================================"
echo "Render.com Quick Deployment Setup"
echo "================================================"
echo ""
echo "1. FORK REPOSITORY:"
echo "   - Go to https://github.com/langflow-ai/langflow"
echo "   - Click 'Fork' in top-right corner"
echo "   - Select your account"
echo ""
echo "2. PUSH BRANCH TO FORK:"
echo "   git remote add fork https://github.com/YOUR_USERNAME/langflow.git"
echo "   git push fork mcp-integration-clean"
echo ""
echo "3. CREATE RENDER SERVICE:"
echo "   Open: https://render.com/new/web"
echo "   Connect your forked repository"
echo "   Select branch: mcp-integration-clean"
echo ""
echo "4. CONFIGURE SERVICE:"
echo "   Name: langflow-mcp"
echo "   Environment: Docker"
echo "   Dockerfile Path: ./docker/build_and_push_mcp.Dockerfile"
echo "   Plan: Standard (recommended)"
echo ""
echo "5. SET ENVIRONMENT VARIABLES:"
echo "   Use values from: deploy/config/render_env_config.json"
echo "   Required API keys:"
echo "     - OPENAI_API_KEY"
echo "     - ANTHROPIC_API_KEY"
echo "     - GOOGLE_API_KEY"
echo "     - DEEPSEEK_API_KEY"
echo "     - ZAI_API_KEY"
echo "     - GROQ_API_KEY"
echo ""
echo "6. CREATE DATABASE:"
echo "   Create PostgreSQL database named 'opencode_taskbus'"
echo "   Link to web service"
echo ""
echo "7. ADD PERSISTENT DISK:"
echo "   Name: langflow-mcp-data"
echo "   Mount Path: /app/data"
echo "   Size: 1GB"
echo ""
echo "8. DEPLOY:"
echo "   Click 'Create Web Service'"
echo "   Monitor build logs"
echo ""
echo "9. TEST DEPLOYMENT:"
echo "   Health check: https://langflow-mcp.onrender.com/health"
echo "   UI: https://langflow-mcp.onrender.com"
echo ""
echo "For detailed instructions, see RENDER_DEPLOYMENT_GUIDE.md"
echo "================================================"
