#!/usr/bin/env python3
"""
Generate Render.com environment variable configuration
This script creates a JSON configuration file that can be imported into Render.com
"""

import json
import os
from pathlib import Path


def generate_render_env_config():
    """Generate Render.com environment variable configuration"""

    # Core Langflow configuration
    core_config = {
        "LANGFLOW_DATABASE_URL": {
            "value": "sqlite:////app/data/.cache/langflow/langflow.db",
            "description": "Database URL for Langflow (SQLite for simplicity)",
        },
        "LANGFLOW_HOST": {"value": "0.0.0.0", "description": "Host to bind the server to"},
        "LANGFLOW_PORT": {"value": "10000", "description": "Port to run the server on (Render.com default)"},
        "LANGFLOW_LOG_LEVEL": {"value": "INFO", "description": "Logging level"},
        "LANGFLOW_AUTO_LOGIN": {"value": "false", "description": "Disable auto-login for security"},
    }

    # MCP Configuration
    mcp_config = {
        "OPENCODE_CONFIG_DIR": {"value": "/app/.opencode", "description": "OpenCode configuration directory"},
        "OPENCODE_AI_DIR": {"value": "/app/.ai", "description": "OpenCode AI artifacts directory"},
        "OPENCODE_SCRIPTS_DIR": {"value": "/app/scripts", "description": "OpenCode scripts directory"},
        "OPENCODE_STRICT_GATES": {"value": "1", "description": "Enable strict gate workflow (A->B->C->D)"},
    }

    # PostgreSQL TaskBus Configuration
    postgres_config = {
        "POSTGRES_HOST": {
            "value": "[Render will provide this]",
            "description": "PostgreSQL host (auto-set by Render when linking database)",
            "sync": False,
        },
        "POSTGRES_PORT": {"value": "5432", "description": "PostgreSQL port"},
        "POSTGRES_DB": {"value": "opencode_taskbus", "description": "PostgreSQL database name"},
        "POSTGRES_USER": {"value": "postgres", "description": "PostgreSQL username"},
        "POSTGRES_PASSWORD": {
            "value": "[Render will generate this]",
            "description": "PostgreSQL password (auto-generated by Render)",
            "generateValue": True,
        },
    }

    # API Keys Configuration (to be filled by user)
    api_keys_config = {
        "OPENAI_API_KEY": {
            "value": "",
            "description": "OpenAI API key (required for GPT models)",
            "sync": False,
            "required": True,
        },
        "ANTHROPIC_API_KEY": {
            "value": "",
            "description": "Anthropic API key (required for Claude models)",
            "sync": False,
            "required": True,
        },
        "GOOGLE_API_KEY": {
            "value": "",
            "description": "Google AI API key (required for Gemini models)",
            "sync": False,
            "required": True,
        },
        "DEEPSEEK_API_KEY": {
            "value": "",
            "description": "DeepSeek API key (required for DeepSeek models)",
            "sync": False,
            "required": True,
        },
        "ZAI_API_KEY": {
            "value": "",
            "description": "Z.AI API key (required for GLM models)",
            "sync": False,
            "required": True,
        },
        "GROQ_API_KEY": {
            "value": "",
            "description": "Groq API key (required for Llama models)",
            "sync": False,
            "required": True,
        },
        "PERPLEXITY_API_KEY": {
            "value": "",
            "description": "Perplexity API key (required for search)",
            "sync": False,
            "required": False,
        },
        "TAVILY_API_KEY": {
            "value": "",
            "description": "Tavily API key (required for web search)",
            "sync": False,
            "required": False,
        },
        "GITHUB_TOKEN": {
            "value": "",
            "description": "GitHub Personal Access Token (for GitHub integration)",
            "sync": False,
            "required": False,
        },
    }

    # Deployment Configuration
    deployment_config = {
        "RENDER": {"value": "true", "description": "Indicates running on Render.com"},
        "HEALTH_CHECK_PATH": {"value": "/health", "description": "Health check endpoint path"},
        "HEALTH_CHECK_TIMEOUT": {"value": "30", "description": "Health check timeout in seconds"},
        "CORS_ORIGINS": {
            "value": "https://*.onrender.com,http://localhost:3000",
            "description": "Allowed CORS origins",
        },
    }

    # Combine all configurations
    all_config = {**core_config, **mcp_config, **postgres_config, **api_keys_config, **deployment_config}

    return all_config


def generate_json_config():
    """Generate JSON configuration file"""
    config = generate_render_env_config()

    # Create output directory
    output_dir = Path("deploy/config")
    output_dir.mkdir(parents=True, exist_ok=True)

    # Save JSON configuration
    output_file = output_dir / "render_env_config.json"
    with open(output_file, "w") as f:
        json.dump(config, f, indent=2)

    print(f"[OK] Configuration generated: {output_file}")

    # Also generate a shell script for manual setup
    generate_shell_script(config)

    return output_file


def generate_shell_script(config):
    """Generate a shell script for manual environment setup"""
    script_content = """#!/bin/bash
# Render.com Environment Variables Setup Script
# Generated from generate_render_env_config.py

echo "================================================"
echo "Render.com Environment Variables Setup"
echo "================================================"
echo ""
echo "Copy and paste the following commands into Render.com dashboard:"
echo ""
echo "1. Go to your web service on Render.com"
echo "2. Click on 'Environment'"
echo "3. Add the following environment variables:"
echo ""

# Group variables by category
categories = {
    "Core Langflow Configuration": [],
    "MCP Configuration": [],
    "PostgreSQL TaskBus": [],
    "API Keys (REQUIRED)": [],
    "Deployment Configuration": []
}

# Categorize variables
for key, value in config.items():
    if key.startswith("LANGFLOW_"):
        categories["Core Langflow Configuration"].append((key, value))
    elif key.startswith("OPENCODE_") or key.startswith("MCP_"):
        categories["MCP Configuration"].append((key, value))
    elif key.startswith("POSTGRES_"):
        categories["PostgreSQL TaskBus"].append((key, value))
    elif "API" in key or "KEY" in key or "TOKEN" in key:
        categories["API Keys (REQUIRED)"].append((key, value))
    else:
        categories["Deployment Configuration"].append((key, value))

# Generate the script
for category, variables in categories.items():
    if variables:
        print(f"\n# {category}")
        print("#" * 50)
        for key, value_info in variables:
            desc = value_info.get('description', '')
            val = value_info.get('value', '')
            required = value_info.get('required', False)
            
            if required and not val:
                print(f"# [REQUIRED] {desc}")
                print(f"# Key: {key}")
                print(f"# Value: [YOUR_{key}_HERE]")
                print("# ---")
            else:
                print(f"# {desc}")
                print(f"# Key: {key}")
                print(f"# Value: {val}")
                print("# ---")

print("")
print("================================================")
print("Important Notes:")
print("================================================")
print("1. For PostgreSQL variables (POSTGRES_*):")
print("   - Render will automatically set these when you link a PostgreSQL database")
print("   - Create a PostgreSQL database named 'opencode_taskbus'")
print("   - Link it to your web service")
print("")
print("2. For API Keys:")
print("   - Get keys from respective provider dashboards")
print("   - Never commit API keys to git")
print("   - Set sync: false for all API keys")
print("")
print("3. After setting variables:")
print("   - Save changes")
print("   - Redeploy the service")
print("   - Check logs for any configuration errors")
print("================================================")
"""

    # Create output directory
    output_dir = Path("deploy/config")
    output_dir.mkdir(parents=True, exist_ok=True)

    # Save shell script
    script_file = output_dir / "setup_render_env.sh"
    with open(script_file, "w") as f:
        f.write(script_content)

    # Make it executable
    os.chmod(script_file, 0o755)

    print(f"[OK] Shell script generated: {script_file}")
    print(f"\nTo use the shell script:")
    print(f"   chmod +x {script_file}")
    print(f"   ./{script_file}")


if __name__ == "__main__":
    print("Generating Render.com environment configuration...")
    config_file = generate_json_config()
    print(f"\n[OK] Configuration file created: {config_file}")
    print("\nNext steps:")
    print("1. Review the configuration file: deploy/config/render_env_config.json")
    print("2. Fill in your API keys in the JSON file")
    print("3. Use the configuration to set up environment variables in Render.com")
    print("4. Deploy your service")
    print("\nFor detailed instructions, see RENDER_DEPLOYMENT_GUIDE.md")
